CREATE OR REPLACE PROCEDURE RegistrarMatricula(
P_ID_ALUMNO IN MATRICULA.ID_ALUMNO%TYPE,
P_ID_CURSO IN MATRICULA.ID_CURSO%TYPE,
P_ID_SECCION IN MATRICULA.ID_SECCION%TYPE,
P_TIPO_MATRICULA IN MATRICULA.TIPO_MATRICULA%TYPE,
P_FECHA_MATRICULA IN  MATRICULA.FECHA_MATRICULA%TYPE,
P_RESULTADO OUT INTEGER
)
AS

BEGIN    
    
    INSERT INTO MATRICULA (ID_MATRICULA, ID_ALUMNO, ID_CURSO, ID_SECCION, TIPO_MATRICULA, FECHA_MATRICULA )
    VALUES (MATRICULA_SEQ.NEXTVAL,P_ID_ALUMNO, P_ID_CURSO, P_ID_SECCION,P_TIPO_MATRICULA, P_FECHA_MATRICULA );
        
    UPDATE VACANTE SET VACANTES_DISPONIBLES = VACANTES_DISPONIBLES - 1, VACANTES_USADAS = VACANTES_USADAS + 1
    WHERE ID_CURSO = P_ID_CURSO AND ID_SECCION = P_ID_SECCION; 
    
    SELECT 1 INTO P_RESULTADO FROM DUAL;
    
    COMMIT;
    

EXCEPTION
    WHEN OTHERS THEN
        -- En caso de error, hacer un rollback
        ROLLBACK;
        P_RESULTADO := -1;       
END;

--EJECUTAR EL SP
--SET SERVEROUTPUT ON;
--DECLARE P_RESULTADO  INTEGER;
--BEGIN
--  RegistrarMatricula (3,4,4,'VIRTUAL',SYSDATE,P_RESULTADO);
--  DBMS_OUTPUT.put_line(P_RESULTADO);
--END;